apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nagp-api-ingress
  namespace: nagp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: nagp-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nagp-api-service
                port:
                  number: 80
